### ISSUE TITLE
Fix: authorization 없이 API 접근 가능

### ISSUE THREAD

**Issue by melitina915** [Codiary-UMC-6th/Backend-Codiary#156]
## 🍒 IssueName
> 이슈 명을 작성해주세요.

Fix: authorization 없이 API 접근 가능

## 📝 Description
> 이슈에 대해 간결하게 설명해주세요.

SecurityConfig.java
authorizeHttpRequests
requestMatchers
permitAll()
에 API 추가

## 🌱 Todo
- [x] 댓글 + 대댓글 개수 조회
- [x] 인기글 전체 리스트 조회
- [x] 최신글 리스트 조회
- [x] 게시글의 댓글&대댓글 조회
- [x] 게시글의 북마크 개수 조회
