### ISSUE TITLE
Refactor: 전반적인 코드 리팩토링 진행

### ISSUE THREAD

**Issue by yumzen** [Codiary-UMC-6th/Backend-Codiary#173]
## 🍒 IssueName
> Refactor: 전반적인 코드 리팩토링 진행

## 📝 Description
리팩토링 화이팅 합시다 ~!
리팩토링 진행했으면 하는 부분은 언제든 편하게 추가해주세요 😆

## 🌱 Todo
- [ ] service 인터페이스/구현체 분리 적용하기
- [ ] 모든 생성자 함수는 `@AllArgsConstructor`가 아닌 `@Builder` 사용해서 빌더 패턴 적용하기
- [ ] Entity에서 `@Setter`, `@Data` 사용하지 않고 직접 setter 역할 메소드를 만들어 적용하기
- [ ] Lazy Initialize Proxy 에러 Fetch Join을 이용하여 해결하기 (OSIV, EAGER, 강제 초기화 지양하기)
- [ ] Service 인터페이스에 접근 제한자 제거하기
- [ ] Controller에서 response 스웨거 적용을 위해 responseCode → SuccessStatus/ErrorStatus 값 적용하기
