### ISSUE TITLE
Feat: 사용자 정보 조회 및 수정

### ISSUE THREAD

**Issue by yumzen** [Codiary-UMC-6th/Backend-Codiary#79]
## 🍒 IssueName
> Feat: 사용자 정보 조회 및 수정

## 📝 Description
> 사용자 정보 조회 및 수정 기능 개발

## 🌱 Todo
- [x] 마이페이지 기본 정보 조회
- [x] 사용자 정보 조회
- [x] 사용자 정보 수정
